main: com.delphinadrealms.Main
name: Tickets
version: 1.0
author: Hank
description: Tickets
commands:
    ticket:
      description: Tickets
      usage: /ticket <args>
      permission: tickets.ticket